ARG ARCH
FROM ${ARCH}/golang:1.13-stretch

COPY . minfs-docker-plugin
WORKDIR minfs-docker-plugin

RUN set -ex \
    && GO111MODULE=on go install --ldflags '-s -w' \
    && mv -f /go/bin/docker-plugin /go/bin/minfs-docker-plugin

CMD ["/go/bin/minfs-docker-plugin"]
