ARG ARCH
FROM ${ARCH}/golang:1.7-wheezy

WORKDIR /go/src/github.com/minio

RUN \
    mkdir -p {/run/docker/plugins,/usr/share/man/man8} && \
    apt-get update && apt-get upgrade -y && \
    apt-get install sudo fuse libfuse2 bash git -y && \
    git clone https://github.com/minio/minfs && \
    cd minfs && \
    make install

COPY minfs-docker-plugin /usr/sbin/minfs-docker-plugin

CMD ["minfs-docker-plugin"]
