.TH mount.minfs 8 "MinFS mount wrapper for Object Storage" "23 January 2021" "MinIO, Inc."
.SH NAME
MinFS \- fuse driver for Object Storage
.SH SYNOPSIS
.B mount -t minfs -o<options> <endpoint>/<bucket> <mountpoint>
.PP
.SH DESCRIPTION
This tool is part of \fBminfs\fR(8) package, which is used to mount using
MinFS native binary.

\fBmount.minfs\fR is meant to be used by the mount(8) command for mounting
native MinFS client. This subcommand, however, can also be used as a
standalone command with limited functionality.

.SH OPTIONS

.SS "Miscellaneous Options"
.PP
.TP

\fB\-h, \fB\-\-help\fR
Show help.
.TP
\fB\-V, \fB\-\-version\fR
Print the minfs version.

.PP
.TP
.I /etc/fstab
A typical MinFS entry in /etc/fstab looks like below

\fBhttp://server1/bucket  /mnt/bucket  minfs defaults   0  0\fR

.TP
.I /proc/mounts
An example entry of a MinFS mountpoint in /proc/mounts looks like below

\fBMinFS /mnt/ramdisk fuse.MinFS rw,nosuid,nodev,relatime,user_id=0,group_id=0 0 0\fR

.SH SEE ALSO
.nf
\fBfusermount\fR(1), \fBmount.minfs\fR(8)
\fR
.fi
.SH COPYRIGHT
.nf
Copyright(c) 2021 MinIO, Inc.  <https://www.min.io>
\fR
.fi
